BEGIN;
\ir assert-rejected.sql
DO $$
DECLARE actor uuid:='20000000-0000-4000-8000-000000000002'; viewer uuid:='20000000-0000-4000-8000-000000000003'; workspace uuid:=(SELECT id FROM public.workspaces WHERE slug='default-workspace'); audience uuid[]; template uuid; schedule uuid; occurrence uuid; rev integer; delivery uuid; snapshot jsonb; responses jsonb;
BEGIN
 SELECT ARRAY[id] INTO audience FROM public.workspace_member_types WHERE workspace_id=workspace AND is_default;
 template:=public.save_scheduled_template(actor,workspace,jsonb_build_object('name','Resend test','messageType','pre_attendance','body','{{title}}','fields',jsonb_build_object('title','Updated service'),'audience',to_jsonb(audience),'attendanceGroups','[{"id":"00000000-0000-4000-8000-000000000011","label":"Noon"},{"id":"00000000-0000-4000-8000-000000000012","label":"Evening"}]'::jsonb));
 schedule:=public.create_scheduled_schedule(actor,workspace,jsonb_build_object('templateId',template,'groupChatId','-1000000000001','startsOn',current_date,'frequency','once','expiryHours',72,'autoSend',false));
 SELECT id,revision INTO STRICT occurrence,rev FROM public.scheduled_message_occurrences WHERE schedule_id=schedule;
 PERFORM pg_temp.assert_rejected(format('SELECT public.request_scheduled_resend(%L,%L,%s)',actor,occurrence,rev),'cannot be resent');
 PERFORM public.request_scheduled_send(actor,occurrence);
 SELECT id INTO STRICT delivery FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='send';
 UPDATE public.notification_deliveries SET status='processing' WHERE id=delivery;
 PERFORM public.begin_scheduled_delivery(delivery);
 PERFORM public.finish_scheduled_delivery(delivery,rev,77441);
 UPDATE public.notification_deliveries SET status='sent' WHERE id=delivery;
 PERFORM public.respond_scheduled_attendance(viewer,occurrence,rev,'attending','07:30','00000000-0000-4000-8000-000000000011');
 SELECT revision INTO rev FROM public.scheduled_message_occurrences WHERE id=occurrence;
 UPDATE public.scheduled_message_occurrences SET delivery_lease=gen_random_uuid(),lease_until=clock_timestamp()+interval '1 minute' WHERE id=occurrence;
 PERFORM pg_temp.assert_rejected(format('SELECT public.request_scheduled_resend(%L,%L,%s)',actor,occurrence,rev),'delivery is in progress');
 UPDATE public.scheduled_message_occurrences SET delivery_lease=NULL,lease_until=NULL WHERE id=occurrence;
 SELECT jsonb_agg(to_jsonb(r) ORDER BY user_id) INTO responses FROM public.scheduled_message_responses r WHERE occurrence_id=occurrence;
 PERFORM pg_temp.assert_rejected(format('SELECT public.request_scheduled_resend(%L,%L,%s)',viewer,occurrence,rev),'Not authorised');
 PERFORM public.request_scheduled_resend(actor,occurrence,rev);
 PERFORM pg_temp.assert_rejected(format('SELECT public.request_scheduled_resend(%L,%L,%s)',actor,occurrence,rev),'changed');
 IF (SELECT count(*) FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend')<>1 THEN RAISE EXCEPTION 'Duplicate resend queued'; END IF;
 IF EXISTS(SELECT 1 FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='edit' AND status IN ('pending','processing')) THEN RAISE EXCEPTION 'Old edit delivery was not superseded'; END IF;
 SELECT revision INTO rev FROM public.scheduled_message_occurrences WHERE id=occurrence;
 PERFORM public.request_scheduled_resend(actor,occurrence,rev);
 IF (SELECT count(*) FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend')<>1 THEN RAISE EXCEPTION 'Pending resend request duplicated delivery'; END IF;
 SELECT id INTO STRICT delivery FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend';
 UPDATE public.notification_deliveries SET status='processing' WHERE id=delivery;
 snapshot:=public.begin_scheduled_delivery(delivery);
 IF snapshot->'responses' IS DISTINCT FROM (SELECT jsonb_agg(to_jsonb(r) ORDER BY name,user_id) FROM public.scheduled_message_responses r WHERE occurrence_id=occurrence) OR snapshot->'occurrence'->'fields'->>'title'<>'Updated service' THEN RAISE EXCEPTION 'Resend lost current content/responses'; END IF;
 PERFORM public.finish_scheduled_delivery(delivery,rev,88552);
 UPDATE public.notification_deliveries SET status='sent' WHERE id=delivery;
 IF (SELECT telegram_message_id FROM public.scheduled_message_occurrences WHERE id=occurrence)<>88552 OR (SELECT state FROM public.scheduled_message_occurrences WHERE id=occurrence)<>'sent' THEN RAISE EXCEPTION 'Resend did not store new Telegram identity'; END IF;
 IF responses IS DISTINCT FROM (SELECT jsonb_agg(to_jsonb(r) ORDER BY user_id) FROM public.scheduled_message_responses r WHERE occurrence_id=occurrence) OR NOT (SELECT roster_frozen FROM public.scheduled_message_occurrences WHERE id=occurrence) THEN RAISE EXCEPTION 'Resend changed the roster or responses'; END IF;
 -- A definite failure retains the message identity and permits a later retry.
 PERFORM public.request_scheduled_resend(actor,occurrence,rev);
 SELECT revision INTO rev FROM public.scheduled_message_occurrences WHERE id=occurrence;
 SELECT id INTO STRICT delivery FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend' AND status='pending';
 UPDATE public.notification_deliveries SET status='processing' WHERE id=delivery;
 PERFORM public.begin_scheduled_delivery(delivery);
 PERFORM public.finish_scheduled_delivery(delivery,rev,NULL,'Telegram rejected resend',false);
 UPDATE public.notification_deliveries SET status='failed' WHERE id=delivery;
 IF (SELECT state FROM public.scheduled_message_occurrences WHERE id=occurrence)<>'sent' OR (SELECT telegram_message_id FROM public.scheduled_message_occurrences WHERE id=occurrence)<>88552 THEN RAISE EXCEPTION 'Failed resend discarded current identity'; END IF;
 -- An ambiguous outcome blocks automatic retry; recovery also handles crashes.
 PERFORM public.request_scheduled_resend(actor,occurrence,rev);
 SELECT revision INTO rev FROM public.scheduled_message_occurrences WHERE id=occurrence;
 SELECT id INTO STRICT delivery FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend' AND status='pending';
 UPDATE public.notification_deliveries SET status='processing' WHERE id=delivery;
 PERFORM public.begin_scheduled_delivery(delivery);
 PERFORM public.finish_scheduled_delivery(delivery,rev,NULL,'Unknown resend outcome',true);
 PERFORM public.recover_scheduled_deliveries();
 IF (SELECT state FROM public.scheduled_message_occurrences WHERE id=occurrence)<>'unknown' OR (SELECT status FROM public.notification_deliveries WHERE id=delivery)<>'failed' THEN RAISE EXCEPTION 'Ambiguous resend remains retryable'; END IF;
 UPDATE public.scheduled_message_occurrences SET state='sent' WHERE id=occurrence;
 PERFORM public.request_scheduled_resend(actor,occurrence,rev);
 SELECT revision INTO rev FROM public.scheduled_message_occurrences WHERE id=occurrence;
 SELECT id INTO STRICT delivery FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend' AND status='pending';
 UPDATE public.notification_deliveries SET status='processing' WHERE id=delivery;
 PERFORM public.begin_scheduled_delivery(delivery);
 UPDATE public.scheduled_message_occurrences SET lease_until=clock_timestamp()-interval '1 second' WHERE id=occurrence;
 PERFORM public.recover_scheduled_deliveries();
 IF (SELECT state FROM public.scheduled_message_occurrences WHERE id=occurrence)<>'unknown' OR (SELECT status FROM public.notification_deliveries WHERE id=delivery)<>'failed' THEN RAISE EXCEPTION 'Crashed resend remains retryable'; END IF;
 -- Expiry after confirmation still prevents the provider send from starting.
 UPDATE public.scheduled_message_occurrences SET state='sent' WHERE id=occurrence;
 PERFORM public.request_scheduled_resend(actor,occurrence,rev);
 SELECT revision INTO rev FROM public.scheduled_message_occurrences WHERE id=occurrence;
 SELECT id INTO STRICT delivery FROM public.notification_deliveries WHERE scheduled_occurrence_id=occurrence AND scheduled_operation='resend' AND status='pending';
 UPDATE public.notification_deliveries SET status='processing' WHERE id=delivery;
 UPDATE public.scheduled_message_occurrences SET expires_at=clock_timestamp()-interval '1 second' WHERE id=occurrence;
 snapshot:=public.begin_scheduled_delivery(delivery);
 IF snapshot IS NOT NULL OR (SELECT status FROM public.notification_deliveries WHERE id=delivery)<>'failed' THEN RAISE EXCEPTION 'Queued resend ignored expiry'; END IF;
 IF responses IS DISTINCT FROM (SELECT jsonb_agg(to_jsonb(r) ORDER BY user_id) FROM public.scheduled_message_responses r WHERE occurrence_id=occurrence) THEN RAISE EXCEPTION 'Resend failure changed responses'; END IF;
 PERFORM pg_temp.assert_rejected(format('SELECT public.request_scheduled_resend(%L,%L,%s)',actor,occurrence,rev),'cannot be resent');
 IF has_function_privilege('moc_app','public.request_scheduled_resend(uuid,uuid,integer)','EXECUTE') OR has_function_privilege('moc_public','public.request_scheduled_resend(uuid,uuid,integer)','EXECUTE') THEN RAISE EXCEPTION 'Resend RPC accessible without service role'; END IF;
END $$;
ROLLBACK;
