import type { Equipment } from '@/types'

export const mockEquipment: Equipment[] = [
  {
    id: '1',
    name: 'PA System - Large',
    category: 'Audio',
    serial_number: 'PA-2024-001',
    status: 'available',
    location: 'Warehouse A',
    condition: 'excellent',
    last_maintenance: '2026-03-01',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'LED Stage Lights (Set of 8)',
    category: 'Lighting',
    serial_number: 'LT-2024-015',
    status: 'assigned',
    assigned_to: 'Marcus Johnson',
    location: 'Downtown Theater',
    condition: 'good',
    last_maintenance: '2026-02-15',
    created_at: '2025-04-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Portable Projector 4K',
    category: 'Visual',
    serial_number: 'PJ-2024-008',
    status: 'maintenance',
    location: 'Tech Lab',
    condition: 'fair',
    last_maintenance: '2026-03-20',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Wireless Microphone Set (4-pack)',
    category: 'Audio',
    serial_number: 'MC-2024-022',
    status: 'available',
    location: 'Warehouse A',
    condition: 'excellent',
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Folding Stage Platform',
    category: 'Staging',
    serial_number: 'ST-2024-003',
    status: 'assigned',
    assigned_to: 'Community Arts Center',
    location: 'Arts Center - Main Hall',
    condition: 'good',
    last_maintenance: '2026-01-10',
    created_at: '2025-03-05T00:00:00Z',
  },
  {
    id: '6',
    name: 'Camera Kit - Broadcast',
    category: 'Video',
    serial_number: 'CM-2024-011',
    status: 'retired',
    location: 'Storage B',
    condition: 'poor',
    created_at: '2024-01-15T00:00:00Z',
  },
]
