import type { MediaItem, QueueItem } from '@/types'

export const mockMediaItems: MediaItem[] = [
  {
    id: 'media-001',
    title: 'Worship Set Intro Video',
    type: 'video',
    url: 'https://example.com/media/worship-intro.mp4',
    thumbnail_url: 'https://placehold.co/320x180/1a1a2e/ffffff?text=Video',
    metadata: { duration_seconds: 45 },
    created_at: '2026-03-01T08:00:00Z',
  },
  {
    id: 'media-002',
    title: 'Welcome Slide',
    type: 'image',
    url: 'https://example.com/media/welcome-slide.jpg',
    thumbnail_url: 'https://placehold.co/320x180/FF1493/ffffff?text=Image',
    metadata: { default_duration: 10, dimensions: '1920x1080' },
    created_at: '2026-03-02T09:00:00Z',
  },
  {
    id: 'media-003',
    title: 'Sermon Series — "Unshaken" Slides',
    type: 'slides',
    thumbnail_url: 'https://placehold.co/320x180/2d3748/ffffff?text=Slides',
    metadata: {
      slides: [
        { id: 'slide-1', url: 'https://example.com/slides/unshaken-1.jpg', duration: 8 },
        { id: 'slide-2', url: 'https://example.com/slides/unshaken-2.jpg', duration: 8 },
        { id: 'slide-3', url: 'https://example.com/slides/unshaken-3.jpg', duration: 8 },
        { id: 'slide-4', url: 'https://example.com/slides/unshaken-4.jpg', duration: 10 },
      ],
    },
    created_at: '2026-03-05T10:00:00Z',
  },
  {
    id: 'media-004',
    title: 'Pre-Service Ambient Music',
    type: 'audio',
    url: 'https://example.com/media/ambient.mp3',
    thumbnail_url: 'https://placehold.co/320x180/4a5568/ffffff?text=Audio',
    metadata: { duration_seconds: 600 },
    created_at: '2026-03-06T11:00:00Z',
  },
  {
    id: 'media-005',
    title: 'Announcements Graphic',
    type: 'image',
    url: 'https://example.com/media/announcements.jpg',
    thumbnail_url: 'https://placehold.co/320x180/553c9a/ffffff?text=Image',
    metadata: { default_duration: 15, dimensions: '1920x1080' },
    created_at: '2026-03-10T12:00:00Z',
  },
  {
    id: 'media-006',
    title: 'Baptism Highlight Reel',
    type: 'video',
    url: 'https://example.com/media/baptism-reel.mp4',
    thumbnail_url: 'https://placehold.co/320x180/2c7a7b/ffffff?text=Video',
    metadata: { duration_seconds: 180 },
    created_at: '2026-03-12T08:30:00Z',
  },
  {
    id: 'media-007',
    title: 'Offering Moment Slides',
    type: 'slides',
    thumbnail_url: 'https://placehold.co/320x180/744210/ffffff?text=Slides',
    metadata: {
      slides: [
        { id: 'offering-1', url: 'https://example.com/slides/offering-1.jpg', duration: 12 },
        { id: 'offering-2', url: 'https://example.com/slides/offering-2.jpg', duration: 12 },
      ],
    },
    created_at: '2026-03-14T09:00:00Z',
  },
  {
    id: 'media-008',
    title: 'Worship Background Loop',
    type: 'audio',
    url: 'https://example.com/media/worship-loop.mp3',
    thumbnail_url: 'https://placehold.co/320x180/2d3748/ffffff?text=Audio',
    metadata: { duration_seconds: 300 },
    created_at: '2026-03-15T10:00:00Z',
  },
  {
    id: 'media-009',
    title: 'Easter Promo Video',
    type: 'video',
    url: 'https://example.com/media/easter-promo.mp4',
    thumbnail_url: 'https://placehold.co/320x180/8b5cf6/ffffff?text=Video',
    metadata: { duration_seconds: 60 },
    created_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'media-010',
    title: 'Closing Slide',
    type: 'image',
    url: 'https://example.com/media/closing.jpg',
    thumbnail_url: 'https://placehold.co/320x180/dc2626/ffffff?text=Image',
    metadata: { default_duration: 10, dimensions: '1920x1080' },
    created_at: '2026-03-20T09:00:00Z',
  },
]

export const mockQueueItems: QueueItem[] = [
  {
    id: 'queue-001',
    media_item_id: 'media-004',
    media_item: mockMediaItems.find((m) => m.id === 'media-004'),
    broadcast_id: '1',
    display_order: 1,
    status: 'completed',
    config: { duration: 600 },
  },
  {
    id: 'queue-002',
    media_item_id: 'media-002',
    media_item: mockMediaItems.find((m) => m.id === 'media-002'),
    broadcast_id: '1',
    display_order: 2,
    status: 'completed',
    config: { duration: 10 },
  },
  {
    id: 'queue-003',
    media_item_id: 'media-001',
    media_item: mockMediaItems.find((m) => m.id === 'media-001'),
    broadcast_id: '1',
    display_order: 3,
    status: 'playing',
    config: {},
  },
  {
    id: 'queue-004',
    media_item_id: 'media-003',
    media_item: mockMediaItems.find((m) => m.id === 'media-003'),
    broadcast_id: '1',
    display_order: 4,
    status: 'queued',
    config: { background_audio_id: 'media-008', background_audio_volume: 0.4 },
  },
  {
    id: 'queue-005',
    media_item_id: 'media-005',
    media_item: mockMediaItems.find((m) => m.id === 'media-005'),
    broadcast_id: '1',
    display_order: 5,
    status: 'queued',
    config: { duration: 15 },
  },
  {
    id: 'queue-006',
    media_item_id: 'media-006',
    media_item: mockMediaItems.find((m) => m.id === 'media-006'),
    broadcast_id: '1',
    display_order: 6,
    status: 'queued',
    config: {},
  },
  {
    id: 'queue-007',
    media_item_id: 'media-007',
    media_item: mockMediaItems.find((m) => m.id === 'media-007'),
    broadcast_id: '1',
    display_order: 7,
    status: 'queued',
    config: {},
  },
  {
    id: 'queue-008',
    media_item_id: 'media-010',
    media_item: mockMediaItems.find((m) => m.id === 'media-010'),
    broadcast_id: '1',
    display_order: 8,
    status: 'queued',
    config: { duration: 10 },
  },
  {
    id: 'queue-009',
    media_item_id: 'media-009',
    media_item: mockMediaItems.find((m) => m.id === 'media-009'),
    broadcast_id: '2',
    display_order: 1,
    status: 'queued',
    config: {},
  },
  {
    id: 'queue-010',
    media_item_id: 'media-002',
    media_item: mockMediaItems.find((m) => m.id === 'media-002'),
    broadcast_id: '2',
    display_order: 2,
    status: 'queued',
    config: { duration: 10 },
  },
]
