import type { Equipment, EquipmentBooking, EquipmentIssue } from '@/types'

export const mockEquipment: Equipment[] = [
  {
    id: '1',
    name: 'PA System - Large',
    description: 'Professional-grade PA system suitable for outdoor events up to 500 attendees.',
    image_url: 'https://placehold.co/320x180/1a1a2e/ffffff?text=PA+System',
    category: 'Audio',
    serial_number: 'PA-2024-001',
    status: 'available',
    location: 'Warehouse A',
    condition: 'excellent',
    quantity: 3,
    quantity_available: 3,
    last_maintenance: '2026-03-01',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'LED Stage Lights (Set of 8)',
    description: 'RGB LED stage lighting kit with DMX controller and stands.',
    image_url: 'https://placehold.co/320x180/553c9a/ffffff?text=LED+Lights',
    category: 'Lighting',
    serial_number: 'LT-2024-015',
    status: 'in_use',
    assigned_to: 'Marcus Johnson',
    location: 'Downtown Theater',
    condition: 'good',
    quantity: 4,
    quantity_available: 2,
    last_maintenance: '2026-02-15',
    created_at: '2025-04-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Portable Projector 4K',
    description: '4K ultra-bright portable projector for presentations and screenings.',
    image_url: 'https://placehold.co/320x180/2c7a7b/ffffff?text=Projector',
    category: 'Visual',
    serial_number: 'PJ-2024-008',
    status: 'faulty',
    location: 'Tech Lab',
    condition: 'fair',
    quantity: 2,
    quantity_available: 1,
    last_maintenance: '2026-03-20',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Wireless Microphone Set (4-pack)',
    description: 'UHF wireless handheld microphones with receiver unit.',
    image_url: 'https://placehold.co/320x180/FF1493/ffffff?text=Mic+Set',
    category: 'Audio',
    serial_number: 'MC-2024-022',
    status: 'booked',
    location: 'Warehouse A',
    condition: 'excellent',
    quantity: 6,
    quantity_available: 4,
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Folding Stage Platform',
    description: 'Modular folding stage platform, 4x8ft sections.',
    image_url: 'https://placehold.co/320x180/744210/ffffff?text=Stage',
    category: 'Staging',
    serial_number: 'ST-2024-003',
    status: 'in_use',
    assigned_to: 'Community Arts Center',
    location: 'Arts Center - Main Hall',
    condition: 'good',
    quantity: 8,
    quantity_available: 4,
    last_maintenance: '2026-01-10',
    created_at: '2025-03-05T00:00:00Z',
  },
  {
    id: '6',
    name: 'Camera Kit - Broadcast',
    description: 'Professional broadcast camera with tripod and accessories.',
    image_url: 'https://placehold.co/320x180/4a5568/ffffff?text=Camera',
    category: 'Video',
    serial_number: 'CM-2024-011',
    status: 'faulty',
    location: 'Storage B',
    condition: 'poor',
    quantity: 1,
    quantity_available: 0,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '7',
    name: 'Drum Kit - Roland TD-17',
    description: 'Electronic drum kit with mesh pads and module.',
    image_url: 'https://placehold.co/320x180/2d3748/ffffff?text=Drum+Kit',
    category: 'Audio',
    serial_number: 'DK-2024-004',
    status: 'available',
    location: 'Warehouse A',
    condition: 'good',
    quantity: 1,
    quantity_available: 1,
    last_maintenance: '2026-02-20',
    created_at: '2025-07-01T00:00:00Z',
  },
  {
    id: '8',
    name: 'Smoke Machine',
    description: 'Haze machine for stage atmosphere effects.',
    image_url: 'https://placehold.co/320x180/6b21a8/ffffff?text=Smoke+Machine',
    category: 'Lighting',
    serial_number: 'SM-2024-009',
    status: 'available',
    location: 'Warehouse B',
    condition: 'excellent',
    quantity: 2,
    quantity_available: 2,
    created_at: '2025-11-10T00:00:00Z',
  },
]

export const mockBookings: EquipmentBooking[] = [
  {
    id: 'bk-1',
    equipment_id: '2',
    equipment_name: 'LED Stage Lights (Set of 8)',
    quantity: 2,
    status: 'in_use',
    booked_by: 'Marcus Johnson',
    assigned_to: 'Worship Team',
    event: 'Sunday Service',
    start_date: '2026-03-22T08:00:00Z',
    end_date: '2026-03-22T14:00:00Z',
    created_at: '2026-03-18T10:00:00Z',
  },
  {
    id: 'bk-2',
    equipment_id: '5',
    equipment_name: 'Folding Stage Platform',
    quantity: 4,
    status: 'in_use',
    booked_by: 'David Park',
    assigned_to: 'Community Arts Center',
    event: 'Spring Concert',
    start_date: '2026-03-20T06:00:00Z',
    end_date: '2026-03-25T22:00:00Z',
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'bk-3',
    equipment_id: '4',
    equipment_name: 'Wireless Microphone Set (4-pack)',
    quantity: 2,
    status: 'booked',
    booked_by: 'Sarah Chen',
    assigned_to: 'Youth Ministry',
    event: 'Youth Night',
    start_date: '2026-03-30T17:00:00Z',
    end_date: '2026-03-30T21:00:00Z',
    created_at: '2026-03-25T11:00:00Z',
  },
  {
    id: 'bk-4',
    equipment_id: '1',
    equipment_name: 'PA System - Large',
    quantity: 1,
    status: 'booked',
    booked_by: 'Elena Vasquez',
    assigned_to: 'Events Team',
    event: 'Easter Service',
    start_date: '2026-04-05T06:00:00Z',
    end_date: '2026-04-05T15:00:00Z',
    notes: 'Outdoor setup required — need extension cables',
    created_at: '2026-03-20T14:00:00Z',
  },
  {
    id: 'bk-5',
    equipment_id: '2',
    equipment_name: 'LED Stage Lights (Set of 8)',
    quantity: 1,
    status: 'booked',
    booked_by: 'Marcus Johnson',
    assigned_to: 'Worship Team',
    event: 'Good Friday Service',
    start_date: '2026-04-03T16:00:00Z',
    end_date: '2026-04-03T21:00:00Z',
    created_at: '2026-03-22T08:00:00Z',
  },
  {
    id: 'bk-6',
    equipment_id: '1',
    equipment_name: 'PA System - Large',
    quantity: 1,
    status: 'returned',
    booked_by: 'David Park',
    assigned_to: 'Outreach Team',
    event: 'Community Fair',
    start_date: '2026-03-15T09:00:00Z',
    end_date: '2026-03-15T18:00:00Z',
    created_at: '2026-03-10T12:00:00Z',
  },
  {
    id: 'bk-7',
    equipment_id: '4',
    equipment_name: 'Wireless Microphone Set (4-pack)',
    quantity: 2,
    status: 'returned',
    booked_by: 'Elena Vasquez',
    assigned_to: 'Worship Team',
    event: 'Midweek Service',
    start_date: '2026-03-19T18:00:00Z',
    end_date: '2026-03-19T21:00:00Z',
    created_at: '2026-03-17T10:00:00Z',
  },
  // Overdue booking — end_date is in the past but status is still in_use
  {
    id: 'bk-8',
    equipment_id: '5',
    equipment_name: 'Folding Stage Platform',
    quantity: 2,
    status: 'in_use',
    booked_by: 'Sarah Chen',
    assigned_to: 'Drama Ministry',
    event: 'Rehearsal Week',
    start_date: '2026-03-18T08:00:00Z',
    end_date: '2026-03-24T20:00:00Z',
    notes: 'Was supposed to be returned Monday',
    created_at: '2026-03-14T15:00:00Z',
  },
]

export const mockIssues: EquipmentIssue[] = [
  {
    id: 'iss-1',
    equipment_id: '3',
    equipment_name: 'Portable Projector 4K',
    description: 'Projector lens has visible scratches affecting image clarity. Needs professional cleaning or lens replacement.',
    reported_by: 'Elena Vasquez',
    status: 'active',
    created_at: '2026-03-22T09:30:00Z',
  },
  {
    id: 'iss-2',
    equipment_id: '6',
    equipment_name: 'Camera Kit - Broadcast',
    description: 'HDMI output port is damaged — no signal when connected to switcher. Possible internal board issue.',
    reported_by: 'Marcus Johnson',
    status: 'active',
    created_at: '2026-03-20T14:00:00Z',
  },
  {
    id: 'iss-3',
    equipment_id: '2',
    equipment_name: 'LED Stage Lights (Set of 8)',
    description: 'One light in the set flickers intermittently on red channel. DMX address confirmed correct.',
    reported_by: 'David Park',
    status: 'resolved',
    resolved_at: '2026-03-18T11:00:00Z',
    created_at: '2026-03-15T16:00:00Z',
  },
  {
    id: 'iss-4',
    equipment_id: '4',
    equipment_name: 'Wireless Microphone Set (4-pack)',
    description: 'Mic 3 has intermittent audio dropouts at distance >15m. Replaced battery and antenna — issue persists.',
    reported_by: 'Sarah Chen',
    status: 'resolved',
    resolved_at: '2026-03-25T10:00:00Z',
    created_at: '2026-03-23T08:00:00Z',
  },
]
