import type { CueEvent } from '@/types'

export const mockCueEvents: CueEvent[] = [
  {
    id: 'event-001',
    name: 'National Culture Summit 2026',
    description: 'Annual Ministry of Culture Summit bringing together policy makers, artists, and community leaders',
    totalDurationMinutes: 480,
    createdAt: '2026-03-01T08:00:00Z',
    tracks: [
      { id: 'track-001', name: 'Main Stage', color: '#FF1493' },
      { id: 'track-002', name: 'AV & Technical', color: '#3B82F6' },
      { id: 'track-003', name: 'Hospitality', color: '#10B981' },
      { id: 'track-004', name: 'Media & Press', color: '#F59E0B' },
    ],
    cueItems: [
      {
        id: 'cue-001',
        title: 'Doors Open',
        type: 'transition',
        trackId: 'track-003',
        startMinute: 0,
        durationMinutes: 30,
        notes: 'Registration and welcome drinks in foyer',
      },
      {
        id: 'cue-002',
        title: 'AV System Check',
        type: 'wrench',
        trackId: 'track-002',
        startMinute: 0,
        durationMinutes: 20,
        notes: 'Final sound and projection check before guests arrive',
      },
      {
        id: 'cue-003',
        title: 'Opening Ceremony',
        type: 'star',
        trackId: 'track-001',
        startMinute: 30,
        durationMinutes: 30,
        notes: 'National anthem, flag ceremony, welcome address by Minister',
      },
      {
        id: 'cue-004',
        title: 'Press Photo Op',
        type: 'camera',
        trackId: 'track-004',
        startMinute: 30,
        durationMinutes: 15,
        notes: 'Official photography with Minister and dignitaries',
      },
      {
        id: 'cue-005',
        title: 'Keynote: Vision 2040 Cultural Policy',
        type: 'microphone',
        trackId: 'track-001',
        startMinute: 60,
        durationMinutes: 45,
        notes: 'Dr. Amira Hassan presenting the 15-year cultural roadmap',
      },
      {
        id: 'cue-006',
        title: 'Live Stream Goes Live',
        type: 'video',
        trackId: 'track-002',
        startMinute: 60,
        durationMinutes: 300,
        notes: 'Stream remains active through all keynote and panel sessions',
      },
      {
        id: 'cue-007',
        title: 'Morning Break',
        type: 'transition',
        trackId: 'track-003',
        startMinute: 105,
        durationMinutes: 20,
        notes: 'Coffee service in exhibition hall',
      },
      {
        id: 'cue-008',
        title: 'Panel: Heritage & Innovation',
        type: 'users',
        trackId: 'track-001',
        startMinute: 125,
        durationMinutes: 75,
        notes: '5 panelists, 30-min presentations + 45-min open Q&A',
      },
      {
        id: 'cue-009',
        title: 'Lunch Reception',
        type: 'transition',
        trackId: 'track-003',
        startMinute: 200,
        durationMinutes: 60,
        notes: 'Seated lunch for 200 guests — traditional catering',
      },
      {
        id: 'cue-010',
        title: 'Afternoon Workshops (x4 parallel)',
        type: 'users',
        trackId: 'track-001',
        startMinute: 270,
        durationMinutes: 90,
        notes: 'Breakout rooms A–D; capacity 40 each',
      },
      {
        id: 'cue-011',
        title: 'Closing Address',
        type: 'microphone',
        trackId: 'track-001',
        startMinute: 390,
        durationMinutes: 30,
        notes: 'Deputy Minister closing remarks and award presentations',
      },
      {
        id: 'cue-012',
        title: 'Networking Reception',
        type: 'star',
        trackId: 'track-003',
        startMinute: 420,
        durationMinutes: 60,
        notes: 'Canapés and drinks in the gallery space',
      },
    ],
  },
  {
    id: 'event-002',
    name: 'Heritage Music Festival — Al Noor Stage',
    description: 'Evening outdoor music festival celebrating traditional and contemporary cultural music',
    totalDurationMinutes: 240,
    createdAt: '2026-03-10T10:00:00Z',
    tracks: [
      { id: 'track-101', name: 'Performance', color: '#8B5CF6' },
      { id: 'track-102', name: 'Sound & Lights', color: '#EC4899' },
      { id: 'track-103', name: 'Stage Management', color: '#14B8A6' },
    ],
    cueItems: [
      {
        id: 'cue-101',
        title: 'Venue Setup Complete',
        type: 'check-circle',
        trackId: 'track-103',
        startMinute: 0,
        durationMinutes: 10,
        notes: 'Stage, seating, and vendor areas confirmed ready',
      },
      {
        id: 'cue-102',
        title: 'Sound Check — All Acts',
        type: 'speaker',
        trackId: 'track-102',
        startMinute: 0,
        durationMinutes: 60,
        notes: 'Rolling sound checks; house opens at minute 60',
      },
      {
        id: 'cue-103',
        title: 'House Opens',
        type: 'transition',
        trackId: 'track-103',
        startMinute: 60,
        durationMinutes: 30,
        notes: 'Audience enters; background music plays',
      },
      {
        id: 'cue-104',
        title: 'Opening Act: Al Fann Ensemble',
        type: 'music',
        trackId: 'track-101',
        startMinute: 90,
        durationMinutes: 35,
        notes: 'Traditional oud and percussion — 6 musicians',
      },
      {
        id: 'cue-105',
        title: 'Stage Transition',
        type: 'wrench',
        trackId: 'track-103',
        startMinute: 125,
        durationMinutes: 15,
        notes: 'Set changeover between acts',
      },
      {
        id: 'cue-106',
        title: 'Headliner: Layla & The Collective',
        type: 'music',
        trackId: 'track-101',
        startMinute: 140,
        durationMinutes: 75,
        notes: 'Full band, 8 members; pyro cues at minute 160 and 200',
      },
      {
        id: 'cue-107',
        title: 'Encore',
        type: 'star',
        trackId: 'track-101',
        startMinute: 215,
        durationMinutes: 15,
        notes: '2 songs',
      },
      {
        id: 'cue-108',
        title: 'House Lights Up / Crowd Exit',
        type: 'lightbulb',
        trackId: 'track-102',
        startMinute: 230,
        durationMinutes: 10,
        notes: 'Fade house lights up over 60 seconds',
      },
    ],
  },
  {
    id: 'event-003',
    name: 'Youth Arts Exhibition Opening',
    description: 'Opening night for the annual youth arts exhibition at the Cultural District gallery',
    totalDurationMinutes: 120,
    createdAt: '2026-03-15T09:00:00Z',
    tracks: [
      { id: 'track-201', name: 'Programme', color: '#F97316' },
      { id: 'track-202', name: 'Technical', color: '#6366F1' },
    ],
    cueItems: [
      {
        id: 'cue-201',
        title: 'Gallery Setup Final Check',
        type: 'check-circle',
        trackId: 'track-201',
        startMinute: 0,
        durationMinutes: 15,
        notes: 'Confirm all 45 artworks are lit and labelled',
      },
      {
        id: 'cue-202',
        title: 'AV Welcome Loop Playing',
        type: 'video',
        trackId: 'track-202',
        startMinute: 0,
        durationMinutes: 120,
        notes: 'Digital displays showing artist profiles on loop',
      },
      {
        id: 'cue-203',
        title: 'Guests Arrive / Welcome Reception',
        type: 'users',
        trackId: 'track-201',
        startMinute: 15,
        durationMinutes: 30,
        notes: 'Canapés and guided gallery walk',
      },
      {
        id: 'cue-204',
        title: 'Welcome Remarks',
        type: 'microphone',
        trackId: 'track-201',
        startMinute: 45,
        durationMinutes: 15,
        notes: 'Director of Youth Arts + two featured student artists speak',
      },
      {
        id: 'cue-205',
        title: 'Award Presentations',
        type: 'star',
        trackId: 'track-201',
        startMinute: 60,
        durationMinutes: 20,
        notes: 'Top 5 works recognised; certificates and prizes',
      },
      {
        id: 'cue-206',
        title: 'Open Viewing',
        type: 'transition',
        trackId: 'track-201',
        startMinute: 80,
        durationMinutes: 40,
        notes: 'Free exploration; artists available to discuss their work',
      },
    ],
  },
]
