import type { Equipment, EquipmentCheckout } from '@/types'

export const mockEquipment: Equipment[] = [
  {
    id: '1',
    name: 'PA System - Large',
    description: 'Professional-grade PA system suitable for outdoor events up to 500 attendees.',
    image_url: 'https://placehold.co/320x180/1a1a2e/ffffff?text=PA+System',
    category: 'Audio',
    serial_number: 'PA-2024-001',
    status: 'available',
    location: 'Warehouse A',
    condition: 'excellent',
    quantity: 3,
    quantity_available: 3,
    last_maintenance: '2026-03-01',
    created_at: '2025-06-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'LED Stage Lights (Set of 8)',
    description: 'RGB LED stage lighting kit with DMX controller and stands.',
    image_url: 'https://placehold.co/320x180/553c9a/ffffff?text=LED+Lights',
    category: 'Lighting',
    serial_number: 'LT-2024-015',
    status: 'assigned',
    assigned_to: 'Marcus Johnson',
    location: 'Downtown Theater',
    condition: 'good',
    quantity: 4,
    quantity_available: 2,
    last_maintenance: '2026-02-15',
    created_at: '2025-04-10T00:00:00Z',
  },
  {
    id: '3',
    name: 'Portable Projector 4K',
    description: '4K ultra-bright portable projector for presentations and screenings.',
    image_url: 'https://placehold.co/320x180/2c7a7b/ffffff?text=Projector',
    category: 'Visual',
    serial_number: 'PJ-2024-008',
    status: 'maintenance',
    location: 'Tech Lab',
    condition: 'fair',
    quantity: 2,
    quantity_available: 1,
    last_maintenance: '2026-03-20',
    created_at: '2025-08-20T00:00:00Z',
  },
  {
    id: '4',
    name: 'Wireless Microphone Set (4-pack)',
    description: 'UHF wireless handheld microphones with receiver unit.',
    image_url: 'https://placehold.co/320x180/FF1493/ffffff?text=Mic+Set',
    category: 'Audio',
    serial_number: 'MC-2024-022',
    status: 'available',
    location: 'Warehouse A',
    condition: 'excellent',
    quantity: 6,
    quantity_available: 6,
    created_at: '2025-09-01T00:00:00Z',
  },
  {
    id: '5',
    name: 'Folding Stage Platform',
    description: 'Modular folding stage platform, 4x8ft sections.',
    image_url: 'https://placehold.co/320x180/744210/ffffff?text=Stage',
    category: 'Staging',
    serial_number: 'ST-2024-003',
    status: 'assigned',
    assigned_to: 'Community Arts Center',
    location: 'Arts Center - Main Hall',
    condition: 'good',
    quantity: 8,
    quantity_available: 4,
    last_maintenance: '2026-01-10',
    created_at: '2025-03-05T00:00:00Z',
  },
  {
    id: '6',
    name: 'Camera Kit - Broadcast',
    description: 'Professional broadcast camera with tripod and accessories.',
    image_url: 'https://placehold.co/320x180/4a5568/ffffff?text=Camera',
    category: 'Video',
    serial_number: 'CM-2024-011',
    status: 'retired',
    location: 'Storage B',
    condition: 'poor',
    quantity: 1,
    quantity_available: 0,
    created_at: '2024-01-15T00:00:00Z',
  },
]

export const mockCheckouts: EquipmentCheckout[] = [
  {
    id: 'co-1',
    equipment_id: '2',
    equipment_name: 'LED Stage Lights (Set of 8)',
    quantity: 1,
    checked_out_by: 'Marcus Johnson',
    destination: 'Downtown Theater',
    checked_out_at: '2026-03-20T09:00:00Z',
  },
  {
    id: 'co-2',
    equipment_id: '2',
    equipment_name: 'LED Stage Lights (Set of 8)',
    quantity: 1,
    checked_out_by: 'Sarah Chen',
    destination: 'Community Hall B',
    checked_out_at: '2026-03-22T14:00:00Z',
  },
  {
    id: 'co-3',
    equipment_id: '5',
    equipment_name: 'Folding Stage Platform',
    quantity: 2,
    checked_out_by: 'Community Arts Center',
    destination: 'Arts Center - Main Hall',
    checked_out_at: '2026-03-18T08:00:00Z',
  },
  {
    id: 'co-4',
    equipment_id: '5',
    equipment_name: 'Folding Stage Platform',
    quantity: 2,
    checked_out_by: 'David Park',
    destination: 'Riverside Amphitheater',
    checked_out_at: '2026-03-25T10:30:00Z',
  },
  {
    id: 'co-5',
    equipment_id: '3',
    equipment_name: 'Portable Projector 4K',
    quantity: 1,
    checked_out_by: 'Elena Vasquez',
    destination: 'Gallery West',
    checked_out_at: '2026-03-15T11:00:00Z',
    returned_at: '2026-03-17T16:00:00Z',
  },
]
