import type { CultureRequest } from '@/types'
import { mockEquipment } from './mock-equipment'
import { mockMediaItems } from './mock-media'
import { mockRequestVenues } from './mock-request-venues'

export const mockRequests: CultureRequest[] = [
  {
    id: 'req-001',
    title: 'National Day Cultural Exhibition Space',
    who: 'Layla Al-Rashidi',
    what: 'A dedicated exhibition hall for traditional art and crafts showcasing local heritage',
    when: '2026-05-15',
    where: 'Cultural District — Hall B',
    why: 'To commemorate National Day and promote cultural identity among younger generations',
    how: 'Physical exhibition with 20 booths, curated by Ministry cultural team',
    requester_email: 'layla.alrashidi@culture.gov',
    type: 'venue',
    status: 'pending',
    priority: 'high',
    due_date: '2026-04-30',
    info: 'Visitor services team needs wayfinding signage and accessible entry planning signed off before launch.',
    venues: [mockRequestVenues[1]],
    equipment: [mockEquipment[3]],
    media: [mockMediaItems[1]],
    notes: [
      {
        id: 'note-001',
        request_id: 'req-001',
        author: 'Aisha Karim',
        body: 'Venue layout is available. Waiting on final visitor circulation approval.',
        created_at: '2026-03-12T09:00:00Z',
      },
    ],
    assignees: [
      {
        id: 'assign-001',
        request_id: 'req-001',
        member_id: 'member-001',
        member_name: 'Aisha Karim',
      },
    ],
    created_at: '2026-03-10T08:00:00Z',
    updated_at: '2026-03-10T08:00:00Z',
  },
  {
    id: 'req-002',
    title: 'Youth Music Program — Spring Cohort',
    who: 'Omar Bin Khalid',
    what: 'Instrument training and ensemble rehearsals for 40 youth aged 12–18',
    when: '2026-04-01 to 2026-06-30',
    where: 'MOC Music Academy — Rooms 3, 4, and 5',
    why: 'Part of the national arts education initiative to increase youth participation in performing arts',
    how: 'Weekly 2-hour sessions led by resident instructors, with a final recital',
    requester_email: 'omar.binkhalid@culture.gov',
    type: 'program',
    status: 'approved',
    priority: 'medium',
    due_date: '2026-03-25',
    media: [mockMediaItems[5]],
    notes: [
      {
        id: 'note-002',
        request_id: 'req-002',
        author: 'Tariq Al-Hamdan',
        body: 'Approved after confirming instructor availability and room allocations.',
        created_at: '2026-03-18T14:00:00Z',
      },
    ],
    assignees: [
      {
        id: 'assign-002',
        request_id: 'req-002',
        member_id: 'member-002',
        member_name: 'Tariq Al-Hamdan',
      },
    ],
    created_at: '2026-03-05T10:30:00Z',
    updated_at: '2026-03-18T14:00:00Z',
  },
  {
    id: 'req-003',
    title: 'Photography Equipment for Documentary Project',
    who: 'Sara Al-Mansoori',
    what: '2× mirrorless cameras, 3× tripods, lighting kit, and audio recorder',
    when: '2026-04-10 to 2026-04-24',
    where: 'Various field locations across the Eastern Province',
    why: 'Producing a 30-minute documentary on traditional fishing communities for broadcast',
    how: 'Field crew of 4 operating with Ministry-issued equipment',
    requester_email: 's.almansoori@culture.gov',
    type: 'equipment',
    status: 'in_review',
    priority: 'urgent',
    due_date: '2026-04-08',
    info: 'The field crew also needs one branded opener slide for sponsor review sessions.',
    equipment: [mockEquipment[0], mockEquipment[2], mockEquipment[3]],
    media: [mockMediaItems[2], mockMediaItems[7]],
    notes: [
      {
        id: 'note-003',
        request_id: 'req-003',
        author: 'Mariam Al-Sayegh',
        body: 'Audio recorder is still in maintenance. Alternative kit is being checked.',
        created_at: '2026-03-22T11:00:00Z',
      },
    ],
    assignees: [
      {
        id: 'assign-003',
        request_id: 'req-003',
        member_id: 'member-003',
        member_name: 'Mariam Al-Sayegh',
      },
      {
        id: 'assign-004',
        request_id: 'req-003',
        member_id: 'member-002',
        member_name: 'Tariq Al-Hamdan',
      },
    ],
    created_at: '2026-03-20T09:15:00Z',
    updated_at: '2026-03-22T11:00:00Z',
  },
  {
    id: 'req-004',
    title: 'International Guest Speaker Coordination',
    who: 'Ahmad Zayed',
    what: 'Logistics and honorarium for 3 international speakers at the Culture Summit',
    when: '2026-05-20',
    where: 'Grand Conference Centre — Auditorium A',
    why: 'To bring global perspectives on cultural policy to Ministry leadership and partners',
    how: 'Coordination through MOC events team; speakers arriving from UK, Japan, and Brazil',
    requester_email: 'a.zayed@culture.gov',
    type: 'event',
    status: 'rejected',
    priority: 'high',
    due_date: '2026-04-15',
    notes: [
      {
        id: 'note-004',
        request_id: 'req-004',
        author: 'Aisha Karim',
        body: 'Rejected pending revised speaker budget and travel policy approval.',
        created_at: '2026-03-15T09:30:00Z',
      },
    ],
    created_at: '2026-02-28T16:00:00Z',
    updated_at: '2026-03-15T09:30:00Z',
  },
  {
    id: 'req-005',
    title: 'Heritage Archive Digitisation — Phase 2',
    who: 'Nora Al-Harbi',
    what: 'High-resolution scanning of 1,200 historical manuscripts and photographs',
    when: '2026-04-15 to 2026-07-31',
    where: 'National Archive — Digitisation Lab',
    why: 'Preservation of at-risk physical documents and public accessibility via the digital portal',
    how: 'Contracted scanning vendor with in-house quality review by archive team',
    requester_email: 'n.alharbi@culture.gov',
    type: 'media',
    status: 'approved',
    priority: 'medium',
    due_date: '2026-04-10',
    venues: [mockRequestVenues[3]],
    media: [mockMediaItems[0], mockMediaItems[4]],
    notes: [
      {
        id: 'note-005',
        request_id: 'req-005',
        author: 'Yousef Nasser',
        body: 'Vendor onboarding is complete. Awaiting final archive batch manifest.',
        created_at: '2026-03-19T10:00:00Z',
      },
    ],
    assignees: [
      {
        id: 'assign-005',
        request_id: 'req-005',
        member_id: 'member-004',
        member_name: 'Yousef Nasser',
      },
    ],
    created_at: '2026-03-01T12:00:00Z',
    updated_at: '2026-03-19T10:00:00Z',
  },
  {
    id: 'req-006',
    title: 'Community Theatre Funding — Q2',
    who: 'Khalid Al-Dosari',
    what: 'Operational grant for set design, costumes, and venue rental for two productions',
    when: '2026-05-01 to 2026-06-30',
    where: 'Al-Noor Community Theatre',
    why: 'Sustaining grassroots performing arts in underserved districts per the Cultural Access Plan',
    how: 'Direct grant disbursement in two tranches; expenditure reports due at end of each month',
    requester_email: 'k.aldosari@theatre.org',
    type: 'other',
    status: 'pending',
    priority: 'low',
    archived: false,
    venues: [mockRequestVenues[0]],
    created_at: '2026-03-22T14:00:00Z',
    updated_at: '2026-03-22T14:00:00Z',
  },
]
