export const routes = {
    login: 'login',
    signup: 'signup',
    resetPassword: 'reset-password',
    dashboard: 'dashboard',
    requestsOverview: 'requests',
    requestsAllRequests: 'requests/all-requests',
    requestsArchived: 'requests/archived',
    requestsDetail: 'requests/:id',
    requestsReports: 'requests/reports',
    equipmentOverview: 'equipment',
    equipmentInventory: 'equipment/inventory',
    equipmentBookings: 'equipment/bookings',
    equipmentMaintenance: 'equipment/maintenance',
    equipmentDetail: 'equipment/:id',
    equipmentReports: 'equipment/reports',
    broadcastOverview: 'broadcast',
    broadcastMedia: 'broadcast/media',
    broadcastBroadcast: 'broadcast/broadcast',
    cueSheetOverview: 'cue-sheet',
    cueSheetEvent: 'cue-sheet/event',
    cueSheetChecklist: 'cue-sheet/checklist',
} as const