export const routes = {
    login: 'login',
    signup: 'signup',
    resetPassword: 'reset-password',
    dashboard: 'dashboard',
    requestsOverview: 'requests',
    requestsAllRequests: 'requests/all-requests',
    requestsArchived: 'requests/archived',
    requestsDetail: 'requests/:id',
    equipmentOverview: 'equipment',
    equipmentInventory: 'equipment/inventory',
    equipmentBookings: 'equipment/bookings',
    equipmentMaintenance: 'equipment/maintenance',
    equipmentDetail: 'equipment/:id',
    broadcastOverview: 'broadcast',
    broadcastMedia: 'broadcast/media',
    broadcastPlaylists: 'broadcast/playlists',
    broadcastPlaylistDetail: 'broadcast/playlists/:id',
    cueSheetOverview: 'cue-sheet',
    cueSheetEvents: 'cue-sheet/events',
    cueSheetEventDetail: 'cue-sheet/events/:id',
    cueSheetChecklists: 'cue-sheet/checklists',
    cueSheetChecklistDetail: 'cue-sheet/checklist/:id',
    cueSheetTemplates: 'cue-sheet/templates',
} as const
