// Sample data for the settings live-preview. Values are intentionally
// realistic so admins see escaping behaviour (e.g. the & in a title).
// Only the templatable types (the five announcements + two DMs) need
// samples — every other event renders a short follow-up note instead
// (see telegram-notes.ts), built from live tokens, not a preview.

import type { MessageType } from "./template-tokens.js";
import type { TokenValues } from "./render-template.js";

export const SAMPLE_TOKENS: Record<MessageType, TokenValues> = {
  "stream.created": {
    title: "Sunday Service — Worship & Word",
    description: "Live broadcast of the 2nd service",
    scheduledStartTime: "18 May, 9:00 AM",
    actualStartTime: "",
    status: "created",
    privacyStatus: "unlisted",
    isForKids: "No",
    latencyPreference: "normal",
    tags: "service, worship, live",
    createdAt: "17 May, 6:40 PM",
    streamUrl: "https://youtube.com/watch?v=abc123",
  },
  "meeting.created": {
    topic: "Production Team Sync",
    description: "Weekly run-through and assignments",
    startTime: "19 May, 2:00 PM",
    duration: "60 min",
    timezone: "Africa/Harare",
    meetingType: "scheduled",
    waitingRoom: "On",
    recurrenceType: "weekly",
    createdAt: "12 May, 11:00 AM",
    joinUrl: "https://zoom.us/j/123456789",
  },
  "request.created": {
    title: "Lower-third graphic for guest speaker",
    status: "not started",
    priority: "High",
    category: "Graphics",
    requesterName: "Tendai M.",
    requestedBy: "Tendai M.",
    dueDate: "21 May, 5:00 PM",
    createdAt: "18 May, 8:12 AM",
    updatedAt: "18 May, 9:30 AM",
    trackingCode: "REQ-4F2A9C",
    who: "Guest speaker — Dr. A. Banda",
    what: "Name + title lower-third for the 2nd session",
    whenText: "Sunday 2nd service",
    whereText: "Main auditorium",
    why: "Introduce the guest on screen",
    how: "Match the current sermon series template",
    notes: "Spelling confirmed with the office",
    flow: "Session 2 → after worship",
    linkUrl: "https://app.example.com/requests/123",
  },
  "booking.created": {
    title: "Sunday Service Setup",
    status: "booked",
    requesterName: "Rumbi K.",
    bookedBy: "Rumbi K.",
    checkedOutAt: "22 May, 7:00 AM",
    expectedReturnAt: "24 May, 8:00 PM",
    returnedAt: "",
    notes: "Outside shoot — handle with care",
    trackingCode: "BKG-77C1",
    itemCount: "3",
    equipmentName: "Sony FX6",
    equipmentNames: "Sony FX6, Sennheiser MKH-416, Manfrotto tripod",
    equipmentCategory: "Camera",
    equipmentLocation: "Store room B, shelf 2",
    equipmentSerial: "FX6-99213",
    linkUrl: "https://app.example.com/equipment/bookings",
  },
  "venue_booking.created": {
    title: "Youth rehearsal",
    status: "booked",
    requesterName: "Tapiwa N.",
    venueName: "Main Auditorium",
    venueDescription: "Ground floor, east wing",
    eventName: "Youth rehearsal",
    startsAt: "22 May, 6:00 PM",
    endsAt: "22 May, 8:00 PM",
    slotCount: "4",
    duration: "2h",
    repeatPattern: "Every week until 31 December 2026",
    occurrenceCount: "32",
    notes: "Need the stage cleared of the conference chairs",
    trackingCode: "VEN-3B81D0",
    linkUrl: "https://app.example.com/venues/123",
  },
  "assignment.request": {
    title: "Lower-third graphic for guest speaker",
    duty: "Design",
    assigneeName: "Craig C.",
    linkUrl: "https://app.example.com/requests/123",
  },
  "assignment.checklist_item": {
    title: "Check radio mic batteries",
    checklistName: "Pre-service audio",
    checklistDescription: "Audio preparation before the service",
    checklistScheduledAt: "18 May, 7:00 AM",
    sectionName: "Wireless microphones",
    itemChecked: "No",
    assigneeName: "Craig C.",
    linkUrl: "https://app.example.com/checklists/123",
  },
};
