export const routes = {
    login: 'login',
    signup: 'signup',
    resetPassword: 'reset-password',
    passwordRecovery: 'password-recovery',
    dashboard: 'dashboard',
    requests: 'requests',
    requestsDetail: 'requests/:id',
    equipment: 'equipment',
    equipmentDetail: 'equipment/:id',
    bookings: 'bookings',
    bookingDetail: 'bookings/:id',
    streams: 'streams',
    streamDetail: 'streams/stream/:id',
    meetingDetail: 'streams/meeting/:id',
    settings: 'account/settings',
    messageTemplateDetail: 'account/settings/message-templates/:messageType',
    privacy: 'legal/privacy',
    terms: 'legal/terms',
    support: 'support',
    zoomDocs: 'docs/zoom',
} as const
