import { useEffect, useRef } from 'react'
import { registerSW } from 'virtual:pwa-register'
import { useFeedback } from '@moc/ui/components/feedback/feedback-provider'

// Registers the service worker generated by vite-plugin-pwa. When a new
// version of the app is available, shows a dismissible notification with
// a "Reload" action. Silent when offline-ready (no need to interrupt).
export function ServiceWorkerRegistrar() {
  const { notify } = useFeedback()
  const registeredRef = useRef(false)

  useEffect(() => {
    if (registeredRef.current) return
    registeredRef.current = true

    const updateSW = registerSW({
      onNeedRefresh() {
        notify({
          title: 'Update available',
          description: 'A new version of MOC Console is ready.',
          variant: 'info',
          action: {
            label: 'Reload',
            onClick: () => {
              updateSW(true)
            },
          },
        })
      },
    })
  }, [notify])

  return null
}
