import { useEffect, useRef } from 'react'
import { registerSW } from 'virtual:pwa-register'

// Registers the service worker generated by vite-plugin-pwa.
//
// We run in `registerType: 'autoUpdate'` mode (see vite.config.ts) — a new
// SW activates silently as soon as it finishes installing. The user never
// sees a prompt; they get the new version when they next refresh the tab.
//
// Pickup speed depends on how often the browser checks for an updated
// sw.js. The default heuristic is sparse (often only on navigation), so
// we poll explicitly: every 60s plus on tab focus / coming back online.
// That way a refresh after a recent deploy serves the new shell from an
// already-updated cache instead of needing a second refresh.
const UPDATE_INTERVAL_MS = 60_000

export function ServiceWorkerRegistrar() {
  const registeredRef = useRef(false)

  useEffect(() => {
    if (registeredRef.current) return
    registeredRef.current = true

    registerSW({
      onRegisteredSW(_swUrl, registration) {
        if (!registration) return

        const checkForUpdate = () => {
          // update() is a no-op when the SW is already up to date.
          registration.update().catch(() => { /* ignore — transient network */ })
        }

        // Registration lasts for the page lifetime; no cleanup needed.
        window.setInterval(checkForUpdate, UPDATE_INTERVAL_MS)
        window.addEventListener('online', checkForUpdate)
        document.addEventListener('visibilitychange', () => {
          if (document.visibilityState === 'visible') checkForUpdate()
        })
      },
    })
  }, [])

  return null
}
