import { getSupabaseAdmin } from "../../server/supabase-admin.js"
import { processPendingOutboxForEntity } from "../../server/notifications/outbox.js"
import { parsePublicNotificationWake } from "../../server/notifications/public-wake.js"
import { applyCors } from "../../server/cors.js"
import type { ApiRequest, ApiResponse } from "../../server/http.js"

// Public callers can only wake the durable booking.created event generated by
// the submission transaction; routing and message content remain server-side.
export default async function handler(request: ApiRequest, response: ApiResponse) {
  if (applyCors(request, response)) return
  response.setHeader("Content-Type", "application/json")
  if (request.method !== "POST") {
    response.status(405).json({ error: "Method not allowed" })
    return
  }

  const wake = parsePublicNotificationWake(request.body, "booking_id")
  if (!wake) {
    response.status(400).json({ error: "booking_id and tracking_code are required" })
    return
  }

  const admin = getSupabaseAdmin()
  const { data, error } = await admin
    .from("bookings")
    .select("id")
    .eq("id", wake.entityId)
    .eq("tracking_code", wake.trackingCode)
    .maybeSingle()
  if (error) {
    response.status(500).json({ error: error.message })
    return
  }
  if (!data) {
    response.status(404).json({ error: "Booking not found" })
    return
  }

  const result = await processPendingOutboxForEntity("booking", data.id, "booking.created")
  response.status(200).json({ ok: true, ...result })
}
