import { handlePublicNotificationWake } from "../../server/notifications/public-wake.js"
import { applyCors } from "../../server/cors.js"
import type { ApiRequest, ApiResponse } from "../../server/http.js"
import { observeApiRequest } from "../../server/observability.js"

// Public callers can only wake the durable booking.created event generated by
// the submission transaction; routing and message content remain server-side.
async function handleBookingWake(request: ApiRequest, response: ApiResponse): Promise<void> {
  if (applyCors(request, response)) return
  response.setHeader("Content-Type", "application/json")
  await handlePublicNotificationWake(request, response, {
    entityIdField: "booking_id",
    entityType: "booking",
    eventType: "booking.created",
    notFoundMessage: "Booking not found",
  })
}

export default async function handler(request: ApiRequest, response: ApiResponse): Promise<void> {
  await observeApiRequest("notify.booking", request, response, async () => {
    await handleBookingWake(request, response)
  })
}
